name: Generate Logos

on:
  push:
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape imagemagick icnsutils
          pip install uv
      - name: Generate logos and montages
        run: |
          uv run ./tools/generate_logos.py -p -i --montage
      - name: Upload logo pngs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: logos-png
          path: |
            ./logo/generated/*.png
            !./logo/generated/montage.png
      - name: Upload logo svgs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: logos-svg
          path: |
            ./logo/generated/*.svg
      - name: Upload montage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: montage
          path: ./logo/generated/montage.png
      - name: Upload icons
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: icons
          path: |
            ./logo/generated/*-plain-*.png
            ./logo/generated/*.ico
            ./logo/generated/*.icns

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: artifacts
      - name: Archive artifacts
        run: |
          tar vczf logos-svg.tar.gz ./artifacts/logos-svg
          tar vczf logos-png.tar.gz ./artifacts/logos-png
          tar vczf icons.tar.gz ./artifacts/icons
          cp ./artifacts/montage/montage.png .
      - name: Create GitHub release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body:
            ## Logos
            ![Logos montage](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/montage.png)
          files: |
            logos-svg.tar.gz
            logos-png.tar.gz
            icons.tar.gz
            montage.png
